---

- name: Download plexmediaserver deb
  get_url:
    url: "https://downloads.plex.tv/plex-media-server/{{ plexmediaserver_version }}/plexmediaserver_{{ plexmediaserver_version }}_amd64.deb"
    dest: /tmp

- name: Install plexmediaserver deb
  apt:
    deb: "/tmp/plexmediaserver_{{ plexmediaserver_version }}_amd64.deb"

- name: Start and enable plexmediaserver service
  systemd:
    name: plexmediaserver
    state: restarted
    enabled: yes
    daemon_reload: yes
