---

- name: Add the X2Go stable repository
  apt_repository:
    repo: ppa:x2go/stable

- name: Install X2Go, mate and x2gomatebindings
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - x2goserver
    - x2goserver-xsession
    - x2gomatebindings
    - ubuntu-mate-core
    - ubuntu-mate-desktop
