---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: ubuntu/xenial64
    memory: 2048
provisioner:
  name: ansible
  options:
    become: True
  lint:
    name: ansible-lint
scenario:
  name: default
  converge_sequence:
    - create
    - prepare
    - converge
verifier:
  name: testinfra
  options:
    verbose: True
  lint:
    name: flake8
